<a href="https://colab.research.google.com/github/Z3Nkkk/Numerical_methods_of_programming/blob/main/lb_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Знайти матрицю С = AB-BA:

In [ ]:
import numpy as np

arr_A = np.array([[2, 3, 1], [-1, 1, 0], [1, 2, -1]])
arr_B = np.array([[1, 2, 1], [0, 1, 2], [3, 1, 1]])

C = arr_A.dot(arr_B) - arr_B.dot(arr_A)

print(f'C:\n {C}')

C:
 [[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


2. Піднести матриці до степеня:

In [ ]:
import numpy as np

A = np.matrix('5 0 0 0; 0 -2 0 0; 0 0 3 0; 0 0 0 2')

print(pow(A, 2))

[[25  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0  4]]


3. Знайти добуток матриць:

In [2]:
import numpy as np

A = np.matrix('5 8 -4; 6 9 -5; 4 7 -3')
B = np.matrix('3 2 5; 4 -1 3; 9 6 5')

print(f'AB:\n {A.dot(B)}')

AB:
 [[ 11 -22  29]
 [  9 -27  32]
 [ 13 -17  26]]


4.	Обчислити визначники:

In [3]:
import numpy as np

A = np.matrix('1 5 -5; 4 0 3; 2 -10 3')
A_det = np.linalg.det(A)

print(f'Визначник: {round(A_det)}')

Визначник: 200


5.	Обчислити визначники.

In [4]:
import numpy as np

A = np.matrix('2 3 4 1; 1 2 3 4; 3 4 1 2; 4 1 2 3')
A_det = np.linalg.det(A)

print(f'Визначник: {round(A_det)}')

Визначник: -160


6.	Знайти обернену матрицю до матриць:

In [ ]:
import numpy as np

A = np.matrix('2 5 7; 6 3 4; 5 -2 -3')
A_inv = np.linalg.inv(A)

print(np.linalg.inv(A))

[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


7. Визначити ранг матриці:

In [5]:
import numpy as np

A = np.matrix('-2 3 1 -1; 3 2 1 4; 1 2 3 4; 0 2 3 3')
rank = np.linalg.matrix_rank(A)

print(f'Ранг матриці: {rank}')

Ранг матриці: 3


8.	Розв’язати систему лінійних рівнянь методом Крамера. Потім зробити перевірку за допомогою solve() пакету linalg :

In [ ]:
import numpy as np

A = np.matrix('3 -5 3; 1 2 1; 2 7 -1')
B = np.matrix('1; 4; 8')
def kram(A,B):
    det_A = np.linalg.det(A)
    if det_A != 0:
       Ax = np.matrix(A)
       Ay = np.matrix(A)
       Az = np.matrix(A)
       Ax[:, 0] = B
       Ay[:, 1] = B
       Az[:, 2] = B
       x = np.linalg.det(Ax)/det_A
       y =np.linalg.det(Ay)/det_A
       z = np.linalg.det(Az)/det_A
       print("Розв'язування системи лінійних алгебраїчних рівнянь методом Крамера")
       print(f' x = {round(x)}; y = {round(y)}; z = {round(z)};')
    else:
        print("Визначник дорівнює нулю, система не має розв'язків")
    return x,y,z
kram(A,B)
print('Перевірка правильності розв’язання:\n', np.linalg.solve(A,B))


Розв'язування системи лінійних алгебраїчних рівнянь методом Крамера
 x = 1; y = 1; z = 1;
Перевірка правильності розв’язання:
 [[1.]
 [1.]
 [1.]]


8.	Розв’язати систему лінійних рівнянь матричним методом (тобто обчислити обернену матрицю). Потім зробити перевірку за допомогою solve() пакету linalg :

In [ ]:
import numpy as np

A = np.matrix('3 -5 3; 1 2 1; 2 7 -1')
B = np.matrix('1; 4; 8')
A_inv = np.linalg.inv(A)
un = A_inv.dot(B)

print(f'X ={un[0]}; Y ={un[1]}; Z ={un[2]}')
print('Перевірка правильності розв’язання:\n', np.linalg.solve(A,B))

X =[[1.]]; Y =[[1.]]; Z =[[1.]]
Перевірка правильності розв’язання:
 [[1.]
 [1.]
 [1.]]


2.2 Створіть прямокутну матрицю A з N рядками та стовпцями M з випадкових елементів. Знайдіть найнижче значення серед середніх значень для кожного рядка матриці.

In [ ]:
import random as r

N = 4
M = 2
A = np.arange(N*M).reshape(N, M)
aver_st = []

for i in range(N):
  sum = 0
  for j in range(M):
    a = r.randint(-9, 9)
    A[i][j] = a
    sum += a
  aver = sum/M
  aver_st.append(aver)

print(A)
print(f'Найменше середнє значення серед рядків: {min(aver_st)}')

[[ 4 -9]
 [-2  1]
 [ 5 -1]
 [ 6  4]]
Найменше середнє значення серед рядків: -2.5
